Inherit common SSplot Parameters
nmfs-ost/ss3diags pull request #94
Opened 2023-07-25 22:37 UTC by efletcherPIFSC

Created generic functions `SSplotGeneric` , `SSplotGenericLegend`, `SSplotGenericPar`, `SSplotGenericUncertianty` to re-use common parameter documentation that ss3diags SSplot functions, via use roxygen tag`@inheritParams`. Resolves #2. 

Implementation of `SSplotGenericPar` resolves #66.

In addition:
- Included markdown notation to SSplot roxygen code documentation
- Added links to other functions such as r4ss::SS_Summarize, and replaced "TRUE/FALSE" with link to base::Logical
- Values in `subplots`, `indexfleets`, and `punits` are listed in a bulleted list
- Typo fixes

2023-07-26 18:39 UTC, efletcherPIFSC commented
@MOshima-PIFSC 
Is the item description listed in the `subplots` parameter accurate for: 
- `SSPlotModelComp`
- `SSplotEnsemble`
- `SSplotHCxval`
- `SSplotJABBAres`
- `SSplotRetro`
- `SSplotRunsTest`

2023-07-26 19:01 UTC, MOshima-PIFSC commented on R/SSplotEnsemble.R
> +#'  \item `"stock"` Fish Population
I would say stock is 'Stock biomass relative to reference point (B/BMSY)' and harvest 'Harvest rate relative to reference point (F/FMSY)'

2023-07-26 19:02 UTC, MOshima-PIFSC commented on R/SSplotHCxval.R
> +#'  \item `"age"` Age composition data (yet to be tested)
Age composition data has been tested and works, can remove the 'yet to be tested'

2023-07-26 19:23 UTC, MOshima-PIFSC requested changes
Hey @efletcherPIFSC I looked over the subplots descriptions. They look good, I just added a few comments/suggestions to them. Also, I noted it in SSplotRunstest.R but any of the functions that have a quants argument, the same type of bulleted list can be used for those as well.

2023-07-26 19:23 UTC, MOshima-PIFSC commented on R/SSplotHCxval.R
> +#'  \item `"cpue"` Index data
to be consistent with other functions, label cpue as Index of abundance data

2023-07-26 19:23 UTC, MOshima-PIFSC commented on R/SSplotHCxval.R
> +#'  \item `"len"` Length composition data
nit pick but for length and age comp add a dash between the words (Length-composition data and Age-composition data)

2023-07-26 19:23 UTC, MOshima-PIFSC commented on R/SSplotJABBAres.R
> +#'  \item `"len"` Length-composition
nit pick but add data after length-composition, age-composition, and generalized size-composition

2023-07-26 19:23 UTC, MOshima-PIFSC commented on R/SSplotModelcomp.R
> +#'  \item `"Index"` Index
Index of abundance

2023-07-26 19:23 UTC, MOshima-PIFSC commented on R/SSplotModelcomp.R
> +#'  \item `"Recruits"` Recruits
Age-0 recruits

2023-07-26 19:23 UTC, MOshima-PIFSC commented on R/SSplotModelcomp.R
> +#'  \item `"Bratio"` B Ratio denominator
Stock biomass relative to biomass reference point

2023-07-26 19:23 UTC, MOshima-PIFSC commented on R/SSplotRunstest.R
> +#'  \item `"cpue"` Index data
Index of abundance data

2023-07-26 19:23 UTC, MOshima-PIFSC commented on R/SSplotRunstest.R
> +#'  \item `"len"` Length composition data
nit pick again, the dashes between age/length/size composition

2023-07-26 19:23 UTC, MOshima-PIFSC commented on R/SSplotRunstest.R
> +#'  \item `"con"` Conditional age at length data
nit pick Conditional age-at-length data

2023-07-26 19:23 UTC, MOshima-PIFSC commented on R/SSplotRunstest.R
> +#' @param quants optional use of `c("cpue","len","age","con")`, default uses
quants can be broken up into a bulleted list like subplots.

2023-07-26 19:23 UTC, MOshima-PIFSC commented on R/SSplotRunstest.R
> +#' CPUE.
nit pick but should probably change CPUE to "cpue" for clarity

2023-07-31 20:21 UTC, efletcherPIFSC commented
@MOshima-PIFSC  Didn't resolve any git code conflicts. Hence the dirty git conflict code. Fixing that.

2023-07-31 23:36 UTC, MOshima-PIFSC approved these changes
all changes look good. I approve the merge

2023-07-31 23:36 UTC, merged

2025-06-05 01:35 UTC, efletcherPIFSC commented
This also resolves #64, #70